package com.example.ibmmq.consumer;

import com.example.ibmmq.config.MqProperties;
import com.example.ibmmq.messaging.ReceivePort;
import jakarta.inject.Singleton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Consumes (destructive GET) from the business queue. <b>It is this consumption that triggers the COD report.</b>
 *
 * <p><b>COD-on-consume:</b> the COD report is generated by the queue manager at the moment the message
 * is retrieved destructively. There is no JMS API to "ask" for the COD on consumption — it follows
 * automatically from the report options already written to the MQMD by the original message.</p>
 *
 * <p><b>Syncpoint / timing:</b> the consumption runs inside a transacted unit of work (UoW). The COD is
 * generated within that UoW and <em>only becomes available after the commit</em>. If the UoW is rolled
 * back (backout), the COD is not sent and the message returns to the queue — consistent with "really
 * delivered".</p>
 *
 * <p><b>Seam (ADR-0008):</b> this entry point no longer opens its own {@code JMSContext} — it delegates to
 * {@link ReceivePort#receiveWithinUnitOfWork}. The port runs the handler INSIDE the UoW and
 * <b>commits</b> on a normal return (releasing the COD) or <b>rolls back</b> on a throw (no COD); this
 * consumer NEVER calls commit()/rollback() directly. No {@code jakarta.jms.Message} reaches here —
 * the handler sees only the decoded body.</p>
 *
 * <p><b>Observability note (ADR-0008, intentional consequence):</b> the seam exposes only the BODY of
 * the consumed message, NOT the consumed messageId (the {@code handle(String body)} signature is fixed).
 * Therefore the {@code [stage=CONSUME]}/{@code [stage=COMMIT]} lines can no longer bind
 * messageId/correlationId in the MDC — an accepted consequence of the locked seam. The stage tags and
 * body remain on the lines; only the messageId MDC is omitted for these two lines.</p>
 */
@Singleton
public class BusinessMessageConsumer {

    private static final Logger LOG = LoggerFactory.getLogger(BusinessMessageConsumer.class);

    private final ReceivePort receivePort;
    private final MqProperties props;

    public BusinessMessageConsumer(ReceivePort receivePort, MqProperties props) {
        this.receivePort = receivePort;
        this.props = props;
    }

    /**
     * Receives a message from the business queue (with timeout), processes it and commits.
     *
     * @param timeoutMillis maximum time to wait for a message (ms).
     * @return the body of the consumed message, or {@code null} if the timeout expires with no message.
     */
    public String receiveOne(long timeoutMillis) {
        // Transacted unit of work: the port commits on a normal handler return (releasing the COD) or
        // rolls back on a throw (the message returns; no COD). On timeout it returns null without
        // invoking the handler. We never call commit()/rollback() ourselves.
        String body = receivePort.receiveWithinUnitOfWork(props.getBusinessQueue(), timeoutMillis, consumedBody -> {
            // Observability note (ADR-0008): the seam surfaces only the body, not the consumed
            // messageId, so this line cannot bind messageId/correlationId in MDC.
            LOG.info("[stage=CONSUME] Business message consumed (destructive GET): body={}", consumedBody);

            // ... business processing here ...

            return consumedBody;
        });

        if (body == null) {
            LOG.debug("No message on the business queue within the timeout ({} ms)", timeoutMillis);
            return null;
        }

        // The port committed on the handler's normal return — the COD is now released to the report
        // queue. Same observability note: no messageId is available to bind in MDC for this line.
        LOG.info("[stage=COMMIT] Consumption committed (commit): COD released to the report queue");

        return body;
    }
}
